### ISSUE TITLE
calibration

### ISSUE THREAD

**Issue by enazoe** [iliasam/OpenLIDAR#2]
how to calibrate the linear ccd and laser? Do
you have any paper is about it?

**Comment by iliasam** [comment]
Calibration and optic adjustments are the same as in OpenSimpleLidar: https://github.com/iliasam/OpenSimpleLidar/wiki/  
Some adjustment steps are given in the article: https://habr.com/ru/post/393685/  
This project is stopped, so I'm not going to add more information about it.

**Comment by enazoe** [comment]
Thank you . I found this https://sites.google.com/site/todddanko/home/webcam_laser_ranger  ,and I think this method is low accuracy. So I want to find some more precison method.
